config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  get 'categories/index'
  get 'categories/show'
  get 'officers/index'
  get 'officers/show'
  get 'streets/index'
  get 'streets/show'
  get 'tickets/index'
  get 'tickets/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :tickets, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  resources :categories, only: [:index, :show]
  resources :officers, only: [:index, :show]
  resources :streets, only: [:index, :show]
  resources :about, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tickets, dependent: :destroy
  has_many :street_categories
  has_many :streets, through: :street_categories

  validates :name, presence: true, uniqueness: true
  paginates_per 20
end

app/models/officer.rb
class Officer < ApplicationRecord
  has_many :tickets

  validates :name, presence: true, uniqueness: true
  paginates_per 20
end

app/models/street.rb
class Street < ApplicationRecord
  has_many :tickets
  has_many :street_categories
  has_many :categories, through: :street_categories

  validates :name, presence: true, uniqueness: true
  paginates_per 20
end

app/models/street_category.rb
class StreetCategory < ApplicationRecord
  belongs_to :street
  belongs_to :category
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :category
  belongs_to :street
  belongs_to :officer
  validates :ticket_number, :date, :discounted_fine, :full_fine, presence: true
  validates :ticket_number, numericality: true, uniqueness: true

  paginates_per 20
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.page(params[:page])
  end

  def show
    @category = Category.find(params[:id])
    @tickets_in_category = Ticket.where(category_id: params[:id])
    @streets_in_category = StreetCategory.where(category_id: params[:id])
    @distinct_streets_in_category = @streets_in_category.select(:street_id).distinct
  end
end

app/controllers/officers_controller.rb
class OfficersController < ApplicationController
  def index
    @officers = Officer.all.page(params[:page])
  end

  def show
    @officer = Officer.find(params[:id])
    @ticketswritten = Ticket.where(officer_id: params[:id]).page(params[:page])
  end
end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController
  def index
    @streets = Street.includes(:categories).page(params[:page])
  end

  def show
    @street = Street.find(params[:id])
    @streetcategories = StreetCategory.where(street_id: params[:id])
    @distinct_street_categories = @streetcategories.select(:category_id).distinct
    @tickets_on_street = Ticket.where(street_id: params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.includes(:category).page(params[:page])
  end

  def show
    @ticket = Ticket.find(params[:id])
    @category_tickets = Category.where(id: @ticket.category_id)
    @officer_tickets = Officer.where(id: @ticket.officer_id)
    @ticket_on_streets = Street.where(id: @ticket.street_id)
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"

    @tickets = Ticket.where("ticket_number LIKE ?", wildcard_search).page(params[:page])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/officers_helper.rb
module OfficersHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/about/index.html.erb
<h1>About This Site</h1>

<div>
  <p>For this project, two data sources were selected to create a simulated parking ticket site that
  records tickets issued in Winnipeg. The first data source comes from the City of Winnipeg Open Data
  Portal, particularly the "Parking Ticket" dataset. This data was extracted in a .csv file (limited to 1000 records)
  and utilized for extraction to various database tables. The Parking Tickets dataset outlines the type of violation that
  occurred, the streets on which parking tickets were issued, the date they were issued on, the discounted fine, the full fine
  to be paid and points that can be used for mapping data. All data except the points for mapping was used on the site.
  The second data source that was selected was from Faker. This data was used to fake data of police officer’s names that
  issued these tickets, and it was also used to fake a unique code which was used as parking ticket numbers. </p>
  <p>
    With both datasets combined, this website will inform anyone browsing it for information of parking tickets issued
    in Winnipeg, on which streets, the dates the tickets were issued, the associated fines, the police officer that issued
    that ticket and  the type of violation that occurred.
  </p>

  <p>
  The database for this site holds 5 tables, namely: Tickets, Officers, Streets, Street_Categories and Categories.
  The Tickets table contains all the details about the tickets issued including: the ticket number, date, discounted fine,
  full fine,  related officer id and related street. The Officers table contains the  names of 200 officers. The Streets
  table contains the name of the streets on which the tickets were issued. The Categories table contains the name of all
  the violations that occurred. The Street_Categories table is a join table that represents a many to many relationship
  between streets and categories, it contains data to show all the streets that a violation occurred on and all the violations
  that occurred on a street, which is represented by the street_id and category_id.
  </p>

  <p>
  Below is an ERD representation of the relationships in the database
  </p>

   <%= image_tag "Final_ERD_Diagram_Full_Stack.png",  class: 'd-block mx-auto', alt: "Image of ERD Diagram"  %>

  <p>
    <strong>Description:</strong> A ticket can be issued by one officer, but an officer can write many tickets;
    A ticket can be issued on one street, but a street can have many  tickets issued on it;
    A ticket can belong to one category(or have a single violation), but many tickets can be written for a violation;
    A street can have many violations occur on it, and a violation can take place on many streets.
  </p>
</div>

app/views/categories/index.html.erb
<h1>All Violation Categories</h1>

<div class="d-flex flex-row-reverse">
  <%= paginate @categories, theme:'bootstrap-5'%>
</div>
<div class="row">
 <% @categories.each do |category| %>
  <div class="col-sm-3">
    <div class="card h-100" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=category.name%></h5>
        <%= link_to "See violation details", category, class: "btn btn-primary"%>
      </div>
    </div>
</div>
<%end%>
</div>

app/views/categories/show.html.erb
<h1>Violation Category: <%=@category.name%></h1>
<h5>All Tickets and Streets in the "<%=@category.name%>" category</h5>
<div class="row mt-5">
  <div class="col">
  <div class="list-group">
    <div class="list-group-item list-group-item-action active">
      Tickets
    </div>
    <% @tickets_in_category.each do |ticket_in_category|%>
        <%=link_to ticket_in_category.ticket_number, ticket_in_category, class: "list-group-item list-group-item-action"%>
    <%end%>
</div>
</div>
<div class="col">
<div class="list-group">
  <div class="list-group-item list-group-item-action active">
    Streets
  </div>
    <% @distinct_streets_in_category.each do |distinct_street_in_category|%>
        <%=link_to distinct_street_in_category.street.name, distinct_street_in_category.street , class: "list-group-item list-group-item-action"%>
    <%end%>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketsOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
  <div class="container">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "Parking Tickets", tickets_index_path, class: "navbar-brand"%>
  <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse" id="navbar">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
      <%= link_to "Tickets", tickets_index_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "Violation Categories", categories_index_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "Officers", officers_index_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Streets", streets_index_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_index_path, class: "nav-link"%>
      </li>
    </ul>
    <%= form_with(url: search_tickets_path, method: :get, local: true) do %>
        <div class="form-inline my-2 my-lg-0">
            <%= text_field_tag(:keywords, nil, class: "form-control mr-sm-2", placeholder: 'Search a ticket number')%>
            <%=submit_tag("Search", class: "btn btn btn-dark my-2 my-sm-0")%>
        </div>
    <%end%>
  </div>
</nav>
    <%= yield %>
  </div>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </body>
</html>

app/views/officers/index.html.erb
<h1>All Officers</h1>

<div class="d-flex flex-row-reverse">
  <%= paginate @officers, theme:'bootstrap-5'%>
</div>
<div class="row">
 <% @officers.each do |officer| %>
  <div class="col-sm-3">
    <div class="card h-100" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=officer.name%></h5>
        <%= link_to "See officer details", officer, class: "btn btn-primary"%>
      </div>
    </div>
</div>
<%end%>
</div>

app/views/officers/show.html.erb
<h2>All tickets written by Officer <%=@officer.name%></h2>

<div class="d-flex flex-row-reverse">
  <%= paginate @ticketswritten, theme:'bootstrap-5'%>
</div>
<div class="row mt-5">
 <% @ticketswritten.each do |ticketwritten| %>
  <div class="col-sm-3">
    <div class="card h-100" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=ticketwritten.ticket_number%></h5>
        <%= link_to "See ticket details", ticketwritten, class: "btn btn-primary"%>
      </div>
    </div>
</div>
<%end%>
</div>

app/views/streets/index.html.erb
<h1>All Streets</h1>

<div class="d-flex flex-row-reverse">
  <%= paginate @streets, theme:'bootstrap-5'%>
</div>
<div class="row">
 <% @streets.each do |street| %>
  <div class="col-sm-3">
    <div class="card h-100" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=street.name%></h5>
        <%= link_to "See street details", street, class: "btn btn-primary"%>
      </div>
    </div>
</div>
<%end%>
</div>

app/views/streets/show.html.erb
<h2>Street: <%=@street.name%></h2>
<h5>All Tickets and Violations that occured on "<%=@street.name%>" street</h5>
<div class="row mt-5">
  <div class="col">
  <div class="list-group">
    <div class="list-group-item list-group-item-action active">
      Category
    </div>
    <% @distinct_street_categories.each do |distinct_street_category|%>
      <%=link_to distinct_street_category.category.name, distinct_street_category.category, class: "list-group-item list-group-item-action"%>
    <%end%>
</div>
</div>
<div class="col">
<div class="list-group">
  <div class="list-group-item list-group-item-action active">
    Ticket
  </div>
     <% @tickets_on_street.each do |ticket_on_street|%>
    <%=link_to ticket_on_street.ticket_number, ticket_on_street, class: "list-group-item list-group-item-action"%>
  <%end%>
</div>
</div>
</div>

app/views/tickets/index.html.erb
<h1>All Violation Tickets</h1>

<div class="d-flex flex-row-reverse">
  <%= paginate @tickets, theme:'bootstrap-5'%>
</div>
<div class="row">
 <% @tickets.each do |ticket| %>
  <div class="col-sm-3">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= ticket.ticket_number%></h5>
        <%= link_to "See ticket details", ticket, class: "btn btn-primary"%>
      </div>
    </div>
</div>
<%end%>
</div>

app/views/tickets/search.html.erb
<h1 class="mt-5">Search results</h1>
<h4 class="mt-1">
  Your search for <%=params[:keywords]%> found <%= pluralize(@tickets.count, 'ticket')%>
</h4>

<div class="d-flex flex-row-reverse">
  <%= paginate @tickets, theme:'bootstrap-5'%>
</div>
<div class="row mt-5">
 <% @tickets.each do |ticket| %>
  <div class="col-sm-3">
    <div class="card h-100" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=ticket.ticket_number%></h5>
        <%= link_to "See ticket details", ticket, class: "btn btn-primary"%>
      </div>
    </div>
</div>
<%end%>
</div>

app/views/tickets/show.html.erb
<div class="card mt-4" style="width: 50rem;">
  <div class="card-body">

    <h5 class="card-title">Ticket Number: <%=@ticket.ticket_number%></h5>

    <% @category_tickets.each do |category_ticket|%>
    <h6 class="card-subtitle mb-2 text-muted">Category: <%= link_to @ticket.category.name, category_ticket%></h6>
    <%end%>
     <p class="card-text">Issue Date: <%=@ticket.date%></p>
    <% @ticket_on_streets.each do |ticket_on_street|%>
    <p class="card-text">Street Issued On: <%=link_to @ticket.street.name, ticket_on_street%></p>
    <%end%>
    <p class="card-text">Discounted Fine: $<%=@ticket.discounted_fine%></p>
    <p class="card-text">Full Fine: $<%=@ticket.full_fine%></p>
   <% @officer_tickets.each do |officer_ticket|%>
    <p class="card-text">Officer Issued By: <%= link_to @ticket.officer.name, officer_ticket%></p>
    <%end%>
  </div>
</div>